name: terminix
version: "1.1.0"
summary: A tiling terminal emulator
description: |
    A tiling terminal emulator
confinement: devmode  # use "strict" to enforce system access only via declared interfaces

apps:
    terminix:
        command: desktop-launch terminix
        plugs: [home, x11, unity7, gsettings]

parts:
    terminix:
        source: https://github.com/gnunn1/terminix.git
        source-tag: 1.1.0
        plugin: dub
        build-packages:
            - build-essential
            - dmd-bin
            - libphobos2-dev
            - libgtkd3-dev
            - gettext
            - intltool
            - libgtk-3-dev
            - libvte-2.91-dev
            - gsettings-desktop-schemas-dev
        stage-packages:
            - gsettings-desktop-schemas
            - libvte-2.91-0
            - python-nautilus
            - libgtkd3-71
            - libphobos2-71
        after: [desktop/gtk3]
